version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/staffguard_db
      SPRING_DATASOURCE_USERNAME: staffguard_admin
      SPRING_DATASOURCE_PASSWORD: SecurePass123!
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Changed context to frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:443"
    volumes:
      - ./frontend/ssl:/etc/nginx/ssl
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: staffguard_db
      POSTGRES_USER: staffguard_admin
      POSTGRES_PASSWORD: SecurePass123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

